### ISSUE TITLE
Current configuration still has me as admin so I receive internal error notifications.

### ISSUE THREAD

**Issue by TWalkerSMCM** [lhjamieson/COSC4012020#13]
https://github.com/lhjamieson/COSC4012020/blob/177185b416181332f50cd9a021ebd9a9968dc9ea/cd_spec_viewer_web/config/settings/base.py#L228

Here is a description of the admin role: https://docs.djangoproject.com/en/dev/ref/settings/#admins

**Comment by TWalkerSMCM** [comment]
Here as well, I forget trafiks role to be honest but wouldn't hurt to change. https://github.com/lhjamieson/COSC4012020/blob/cca09ac780c28421b51ee0dce2f73d64a91cb465/cd_spec_viewer_web/compose/production/traefik/traefik.yml#L17

**Comment by awhite1432** [comment]
The email addresses at these locations have been replaced with sread@smcm.edu and pushed to master branch. Thanks for the heads up, Thomas!
